# Generated by Django 3.1.7 on 2022-08-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_filmes_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='nota',
        ),
    ]
