# Generated by Django 3.1.7 on 2022-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_filmes_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
