# Generated by Django 3.1.7 on 2022-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_filmes_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
